<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Parallax Template - Materialize</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="assets/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="assets/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.1.0/css/v4-shims.min.css" rel="stylesheet"  media="screen,projection"/>

  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">



</head>
<body onload="splash(2000)">

<div class="deep-purple" style="height: 100vh; width:100%; z-index:10000000000; position:absolute;" id="splashscreen">
  <div style="margin-top: 150px;" class="">
    
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="155px" height="155px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
<circle cx="50" cy="50" fill="none" stroke="#ffffff" stroke-width="10" r="25" stroke-dasharray="117.80972450961724 41.269908169872416">
  <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
</circle>
<!-- [ldio] generated by https://loading.io/ --></svg>

  </div>
</div>
<div id="app-content" style="z-index: -1;">

  <nav class="deep-purple  white-text" role="navigation">
    <div class="nav-wrapper container white-text">
      <a id="logo-container" href="#" class="brand-logo">

      <b>OpenHause</b>

      </a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#">Home</a></li>
        <li><a href="#">Venta</a></li>
        <li><a href="#">Renta</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        
        <div class="user-view">
            <a href=""><img class="circle" src="" alt=""></a>
            <span class="black-text name">Jgomez</span>
            <span class="grey-text darken-3 email">mail@mail.com</span>
        </div>

        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>


     


    </div>
  </nav>

  <header class="white-text valign-wrapper">
    <div style="position: relative;" class="container">
      
      <h1 class="app-title ">Bienes Raices</h1>
      <p class="app-subtitle white-text ">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi, reiciendis quibusdam!</p>


      <form id="search_form" method="POST" action="">

          <div class="col s12 m6">
            <input style="background-color: white;" placeholder="Busca por calle, ciudad o palabra" name="search_input" id="search_input"  type="text" class="validate">
          </div>

      </form>

      <button id="search_button" class="deep-purple waves-effect waves-light btn btn-large">Buscar</button>
      <a href="search.php" class=" white deep-purple-text waves-effect waves-dark btn-large">Busqueda Avanzada</a>
    </div>
  </header>

  
  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">

        <div class="col l12">
          <h3 id="main_title" style="margin-bottom: 85px;">Destacadas</h3>
        </div>
      </div>
      <div >
        <div class="">

          <div class="row" id="load_data"></div>

          <div id="load_data_message"></div>

          <br>
          <br><br><br><br><br><br><br><br><br><br><br><br><br><br>

      
         
        </div>

       
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="assets/images/background2.jpg" alt="Unsplashed background img 2"></div>
  </div>


  

 
  <footer class="page-footer deep-purple">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Nosotros</h5>
          <p class="grey-text text-lighten-4 justify">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Totam aut voluptatibus minus pariatur? Itaque ad, dolorem reprehenderit vero rem labore laboriosam aut impedit placeat quibusdam voluptas facere vel nulla recusandae.</p>


        </div>
        <div class="col l3 s12">
          <!--
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
          -->
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!"><i class="fab fa-facebook-square"></i></a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      <a class="white-text text-lighten-3" href="#">&copy; jlgc-xyz <?php echo date("Y"); ?></a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="assets/js/materialize.js"></script>
  <script src="assets/js/init.js"></script>

  <script>


    $(document).ready(function(){
      var myEl = document.getElementById('search_button');
      var search_input = "";
      var url = "api/v1/fetch.php";
      var limit = 3;
      var start = 0;
      var action = 'inactive';

      myEl.addEventListener('click', function() {
        search_input = $('#search_input').val();  
        //alert('Hello world'+search_input);
        if(search_input != "")
        {
          start = 0;
          $('#load_data').html("");
          $('#main_title').html("Resultados de la busqueda: "+search_input);
          url = "api/v1/fetch.php?search="+search_input;
          //action = active;
          load_data(limit, start);
          $('html, body').animate({
              scrollTop: $("#load_data").offset().top
          }, 2000);
        }
      }, false);

      

      function load_data(limit, start){

        


          $.ajax({
            url:url,
            method:"POST",
            data:{limit:limit, start:start},
            cache:false,
            success:function(data)
            {
                $('#load_data').append(data);
                if(data == '')
                {
                    $('#load_data_message').html("<div><button style='width:100%' class='btn deep-purple'>No Data Found</button></div>");
                    action = 'active';
                }
                else
                {
                    $('#load_data_message').html("<div><button style='width:100%' class='btn deep-purple'>Loading, Please Wait...</button></div>");
                    action = 'inactive';

                }
            }
          })
      }

      if(action == 'inactive')
      {
        action = 'active';
        load_data(limit, start);
      }

      $(window).scroll(function(){
        if($(window).scrollTop() + $(window).height() > $("#load_data").height() && action == 'inactive') 
        {
          //alert("ya");
          action = 'active';
          start = start + limit;
          setTimeout(function(){
            load_data(limit,start);
          },2000);
        }
      });

    });
  </script>

  <script>
    $('#app-content').hide();
    function splash(param) {
      var time = param;
      setTimeout(function () {
        $('#splashscreen').fadeOut("1000");
        $('#app-content').show();
      }, time);
    }
  </script>
</div>  
  </body>

</html>
